"""Add columns

Revision ID: 07fff4f23ca8
Revises: b8e53050d9cc
Create Date: 2026-01-23 11:00:53.344079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '07fff4f23ca8'
down_revision: Union[str, Sequence[str], None] = 'b8e53050d9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('approved_l1_at', sa.DateTime(), nullable=True))
    op.add_column('expenses', sa.Column('approved_l2_at', sa.DateTime(), nullable=True))
    # op.drop_constraint(op.f('expenses_ibfk_5'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'users', ['requester_id'], ['id'])
    # op.drop_column('expenses', 'service_acceptance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('service_acceptance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('expenses_ibfk_5'), 'expenses', 'service_acceptances', ['service_acceptance_id'], ['id'])
    op.drop_column('expenses', 'approved_l2_at')
    op.drop_column('expenses', 'approved_l1_at')
    # ### end Alembic commands ###
