"""add caisse columns

Revision ID: 0fd2cb4a2da1
Revises: f5a34b7e618f
Create Date: 2026-02-17 14:43:11.492180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0fd2cb4a2da1'
down_revision: Union[str, Sequence[str], None] = 'f5a34b7e618f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_request_items', sa.Column('pd_approved_amount', sa.Float(), nullable=True))
    op.add_column('fund_request_items', sa.Column('admin_approved_amount', sa.Float(), nullable=True))
    op.drop_column('fund_request_items', 'approved_amount')
    op.add_column('fund_requests', sa.Column('pd_approver_id', sa.Integer(), nullable=True))
    op.add_column('fund_requests', sa.Column('pd_approved_at', sa.DateTime(), nullable=True))
    op.add_column('fund_requests', sa.Column('admin_approver_id', sa.Integer(), nullable=True))
    op.add_column('fund_requests', sa.Column('admin_approved_at', sa.DateTime(), nullable=True))
    op.add_column('fund_requests', sa.Column('raf_id', sa.Integer(), nullable=True))
    op.add_column('fund_requests', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('fund_requests', sa.Column('pd_validated_amount', sa.Float(), nullable=True))
    op.drop_constraint(op.f('fund_requests_ibfk_1'), 'fund_requests', type_='foreignkey')
    op.create_foreign_key(None, 'fund_requests', 'users', ['raf_id'], ['id'])
    op.create_foreign_key(None, 'fund_requests', 'users', ['pd_approver_id'], ['id'])
    op.create_foreign_key(None, 'fund_requests', 'users', ['admin_approver_id'], ['id'])
    op.drop_column('fund_requests', 'approver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_requests', sa.Column('approver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fund_requests', type_='foreignkey')
    op.drop_constraint(None, 'fund_requests', type_='foreignkey')
    op.drop_constraint(None, 'fund_requests', type_='foreignkey')
    op.create_foreign_key(op.f('fund_requests_ibfk_1'), 'fund_requests', 'users', ['approver_id'], ['id'])
    op.drop_column('fund_requests', 'pd_validated_amount')
    op.drop_column('fund_requests', 'total_amount')
    op.drop_column('fund_requests', 'raf_id')
    op.drop_column('fund_requests', 'admin_approved_at')
    op.drop_column('fund_requests', 'admin_approver_id')
    op.drop_column('fund_requests', 'pd_approved_at')
    op.drop_column('fund_requests', 'pd_approver_id')
    op.add_column('fund_request_items', sa.Column('approved_amount', mysql.FLOAT(), nullable=True))
    op.drop_column('fund_request_items', 'admin_approved_amount')
    op.drop_column('fund_request_items', 'pd_approved_amount')
    # ### end Alembic commands ###
