"""fresh_schema_v2_site_first

Revision ID: 191f264aeeed
Revises: 
Create Date: 2025-11-27 10:02:28.667149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '191f264aeeed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=True)
    op.create_table('customer_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_projects_id'), 'customer_projects', ['id'], unique=False)
    op.create_index(op.f('ix_customer_projects_name'), 'customer_projects', ['name'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=True)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(length=300), nullable=False),
    sa.Column('site_name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_site_code'), 'sites', ['site_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('cin', sa.String(length=50), nullable=True),
    sa.Column('cnss', sa.String(length=50), nullable=True),
    sa.Column('rib', sa.String(length=24), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('SBC', 'QUALITY', 'RAF', 'PM', 'PD', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('daily_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cin'),
    sa.UniqueConstraint('cnss'),
    sa.UniqueConstraint('rib')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('internal_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_type', sa.Enum('FIXED_PRICE', 'TIME_MATERIAL', 'INTERNAL', 'TBD', name='projecttype'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('plan_end_date', sa.Date(), nullable=True),
    sa.Column('has_extension_possibility', sa.Boolean(), nullable=True),
    sa.Column('forecast_plan_details', sa.String(length=1000), nullable=True),
    sa.Column('budget_assigned', sa.Float(), nullable=True),
    sa.Column('budget_period', sa.String(length=50), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('direct_customer_id', sa.Integer(), nullable=True),
    sa.Column('final_customer_id', sa.Integer(), nullable=True),
    sa.Column('project_manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['direct_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['final_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['project_manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_projects_id'), 'internal_projects', ['id'], unique=False)
    op.create_index(op.f('ix_internal_projects_name'), 'internal_projects', ['name'], unique=True)
    op.create_table('raw_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_no', sa.String(length=100), nullable=True),
    sa.Column('po_line_no', sa.Integer(), nullable=True),
    sa.Column('shipment_no', sa.Integer(), nullable=True),
    sa.Column('acceptance_qty', sa.Float(), nullable=True),
    sa.Column('application_processed_date', sa.DateTime(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_acceptances_id'), 'raw_acceptances', ['id'], unique=False)
    op.create_index(op.f('ix_raw_acceptances_is_processed'), 'raw_acceptances', ['is_processed'], unique=False)
    op.create_index(op.f('ix_raw_acceptances_po_no'), 'raw_acceptances', ['po_no'], unique=False)
    op.create_table('upload_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_history_id'), 'upload_history', ['id'], unique=False)
    op.create_table('raw_purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_status', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('line_amount', sa.Float(), nullable=True),
    sa.Column('po_no', sa.String(length=100), nullable=True),
    sa.Column('po_line_no', sa.Integer(), nullable=True),
    sa.Column('item_description', sa.String(length=500), nullable=True),
    sa.Column('requested_qty', sa.Float(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('payment_terms_raw', sa.String(length=500), nullable=True),
    sa.Column('project_code', sa.String(length=260), nullable=True),
    sa.Column('internal_project_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['internal_project_id'], ['internal_projects.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_purchase_orders_customer_id'), 'raw_purchase_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_raw_purchase_orders_id'), 'raw_purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_raw_purchase_orders_internal_project_id'), 'raw_purchase_orders', ['internal_project_id'], unique=False)
    op.create_index(op.f('ix_raw_purchase_orders_is_processed'), 'raw_purchase_orders', ['is_processed'], unique=False)
    op.create_index(op.f('ix_raw_purchase_orders_po_no'), 'raw_purchase_orders', ['po_no'], unique=False)
    op.create_index(op.f('ix_raw_purchase_orders_project_code'), 'raw_purchase_orders', ['project_code'], unique=False)
    op.create_index(op.f('ix_raw_purchase_orders_site_id'), 'raw_purchase_orders', ['site_id'], unique=False)
    op.create_table('site_assignment_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('STARTS_WITH', 'ENDS_WITH', 'CONTAINS', name='site_rule_type_enum'), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('internal_project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['internal_project_id'], ['internal_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_assignment_rules_id'), 'site_assignment_rules', ['id'], unique=False)
    op.create_table('site_project_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_project_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('internal_project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_project_id'], ['customer_projects.id'], ),
    sa.ForeignKeyConstraint(['internal_project_id'], ['internal_projects.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_project_allocations_id'), 'site_project_allocations', ['id'], unique=False)
    op.create_table('merged_pos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.String(length=255), nullable=True),
    sa.Column('raw_po_id', sa.Integer(), nullable=True),
    sa.Column('customer_project_id', sa.Integer(), nullable=False),
    sa.Column('internal_project_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('site_code', sa.String(length=100), nullable=True),
    sa.Column('po_no', sa.String(length=100), nullable=True),
    sa.Column('po_line_no', sa.Integer(), nullable=True),
    sa.Column('item_description', sa.String(length=500), nullable=True),
    sa.Column('payment_term', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('requested_qty', sa.Float(), nullable=True),
    sa.Column('internal_control', sa.Integer(), nullable=True),
    sa.Column('line_amount_hw', sa.Float(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('total_ac_amount', sa.Float(), nullable=True),
    sa.Column('accepted_ac_amount', sa.Float(), nullable=True),
    sa.Column('date_ac_ok', sa.Date(), nullable=True),
    sa.Column('total_pac_amount', sa.Float(), nullable=True),
    sa.Column('accepted_pac_amount', sa.Float(), nullable=True),
    sa.Column('date_pac_ok', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_project_id'], ['customer_projects.id'], ),
    sa.ForeignKeyConstraint(['internal_project_id'], ['internal_projects.id'], ),
    sa.ForeignKeyConstraint(['raw_po_id'], ['raw_purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_po_id')
    )
    op.create_index(op.f('ix_merged_pos_id'), 'merged_pos', ['id'], unique=False)
    op.create_index(op.f('ix_merged_pos_po_id'), 'merged_pos', ['po_id'], unique=True)
    op.create_index(op.f('ix_merged_pos_po_no'), 'merged_pos', ['po_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merged_pos_po_no'), table_name='merged_pos')
    op.drop_index(op.f('ix_merged_pos_po_id'), table_name='merged_pos')
    op.drop_index(op.f('ix_merged_pos_id'), table_name='merged_pos')
    op.drop_table('merged_pos')
    op.drop_index(op.f('ix_site_project_allocations_id'), table_name='site_project_allocations')
    op.drop_table('site_project_allocations')
    op.drop_index(op.f('ix_site_assignment_rules_id'), table_name='site_assignment_rules')
    op.drop_table('site_assignment_rules')
    op.drop_index(op.f('ix_raw_purchase_orders_site_id'), table_name='raw_purchase_orders')
    op.drop_index(op.f('ix_raw_purchase_orders_project_code'), table_name='raw_purchase_orders')
    op.drop_index(op.f('ix_raw_purchase_orders_po_no'), table_name='raw_purchase_orders')
    op.drop_index(op.f('ix_raw_purchase_orders_is_processed'), table_name='raw_purchase_orders')
    op.drop_index(op.f('ix_raw_purchase_orders_internal_project_id'), table_name='raw_purchase_orders')
    op.drop_index(op.f('ix_raw_purchase_orders_id'), table_name='raw_purchase_orders')
    op.drop_index(op.f('ix_raw_purchase_orders_customer_id'), table_name='raw_purchase_orders')
    op.drop_table('raw_purchase_orders')
    op.drop_index(op.f('ix_upload_history_id'), table_name='upload_history')
    op.drop_table('upload_history')
    op.drop_index(op.f('ix_raw_acceptances_po_no'), table_name='raw_acceptances')
    op.drop_index(op.f('ix_raw_acceptances_is_processed'), table_name='raw_acceptances')
    op.drop_index(op.f('ix_raw_acceptances_id'), table_name='raw_acceptances')
    op.drop_table('raw_acceptances')
    op.drop_index(op.f('ix_internal_projects_name'), table_name='internal_projects')
    op.drop_index(op.f('ix_internal_projects_id'), table_name='internal_projects')
    op.drop_table('internal_projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sites_site_code'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_customer_projects_name'), table_name='customer_projects')
    op.drop_index(op.f('ix_customer_projects_id'), table_name='customer_projects')
    op.drop_table('customer_projects')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
