"""Add columns

Revision ID: 1a2a7cd9d778
Revises: 1ba5ccab98b1
Create Date: 2025-12-21 15:23:33.966004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2a7cd9d778'
down_revision: Union[str, Sequence[str], None] = '1ba5ccab98b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bon_de_commandes', sa.Column('bc_type', sa.Enum('STANDARD', 'PERSONNE_PHYSIQUE', name='bctype'), nullable=False))
    op.add_column('merged_pos', sa.Column('assignment_status', sa.Enum('APPROVED', 'PENDING_APPROVAL', 'REJECTED', name='assignmentstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merged_pos', 'assignment_status')
    op.drop_column('bon_de_commandes', 'bc_type')
    # ### end Alembic commands ###
