"""gdcbhcd

Revision ID: 1ba5ccab98b1
Revises: 99e62e80d215
Create Date: 2025-12-17 17:23:08.073829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ba5ccab98b1'
down_revision: Union[str, Sequence[str], None] = '99e62e80d215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
