"""add notif

Revision ID: 1e219541ee41
Revises: 8197a37b527a
Create Date: 2026-02-03 18:19:08.068053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e219541ee41'
down_revision: Union[str, Sequence[str], None] = '8197a37b527a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('module', sa.Enum('BC', 'EXP', 'CAISSE', 'ACCEPTANCE', 'DISPATCH', 'SYSTEM', name='notificationmodule'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'module')
    # ### end Alembic commands ###
