"""Add columns

Revision ID: 21544a1e3cd8
Revises: 1e219541ee41
Create Date: 2026-02-05 13:37:47.991284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21544a1e3cd8'
down_revision: Union[str, Sequence[str], None] = '1e219541ee41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_acceptances', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service_acceptances', 'invoices', ['invoice_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_acceptances', type_='foreignkey')
    op.drop_column('service_acceptances', 'invoice_id')
    # ### end Alembic commands ###
