"""project and site link

Revision ID: 21bbc02425f1
Revises: 42b6eb9a345f
Create Date: 2025-11-17 11:58:39.772018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21bbc02425f1'
down_revision: Union[str, Sequence[str], None] = '42b6eb9a345f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merged_pos', sa.Column('project_name', sa.String(length=255), nullable=True))
    op.add_column('merged_pos', sa.Column('site_code', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merged_pos', 'site_code')
    op.drop_column('merged_pos', 'project_name')
    # ### end Alembic commands ###
