"""Add filenames to SBC

Revision ID: 229c335ab0b9
Revises: ce6263ad171c
Create Date: 2026-01-06 10:07:04.007486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229c335ab0b9'
down_revision: Union[str, Sequence[str], None] = 'ce6263ad171c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sbcs', sa.Column('contract_filename', sa.String(length=255), nullable=True))
    op.add_column('sbcs', sa.Column('tax_reg_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sbcs', 'tax_reg_filename')
    op.drop_column('sbcs', 'contract_filename')
    # ### end Alembic commands ###
