"""Add AC/PAC and category columns to MergedPO table

Revision ID: 2540623cc83e
Revises: bfca8f62ac62
Create Date: 2025-11-12 17:37:07.051050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2540623cc83e'
down_revision: Union[str, Sequence[str], None] = 'bfca8f62ac62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merged_pos', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('merged_pos', sa.Column('total_ac_amount', sa.Float(), nullable=True))
    op.add_column('merged_pos', sa.Column('accepted_ac_amount', sa.Float(), nullable=True))
    op.add_column('merged_pos', sa.Column('date_ac_ok', sa.Date(), nullable=True))
    op.add_column('merged_pos', sa.Column('total_pac_amount', sa.Float(), nullable=True))
    op.add_column('merged_pos', sa.Column('accepted_pac_amount', sa.Float(), nullable=True))
    op.add_column('merged_pos', sa.Column('date_pac_ok', sa.Date(), nullable=True))
    op.add_column('purchase_orders', sa.Column('item_code_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_orders', 'item_code_description')
    op.drop_column('merged_pos', 'date_pac_ok')
    op.drop_column('merged_pos', 'accepted_pac_amount')
    op.drop_column('merged_pos', 'total_pac_amount')
    op.drop_column('merged_pos', 'date_ac_ok')
    op.drop_column('merged_pos', 'accepted_ac_amount')
    op.drop_column('merged_pos', 'total_ac_amount')
    op.drop_column('merged_pos', 'category')
    # ### end Alembic commands ###
