"""Add item_description

Revision ID: 2791e3b5e816
Revises: 2540623cc83e
Create Date: 2025-11-12 22:00:37.458913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2791e3b5e816'
down_revision: Union[str, Sequence[str], None] = '2540623cc83e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('item_description', sa.String(length=500), nullable=True))
    op.drop_column('purchase_orders', 'item_code_description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('item_code_description', mysql.VARCHAR(length=500), nullable=True))
    op.drop_column('purchase_orders', 'item_description')
    # ### end Alembic commands ###
