"""add_bc_tables_and_tax_rules

Revision ID: 2d1702a2b1ed
Revises: 40fd8262930e
Create Date: 2025-12-05 12:33:03.965495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d1702a2b1ed'
down_revision: Union[str, Sequence[str], None] = '40fd8262930e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'year', name='uix_tax_category_year')
    )
    op.create_index(op.f('ix_tax_rules_id'), 'tax_rules', ['id'], unique=False)
    op.create_table('sbcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sbc_code', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('UNDER_APPROVAL', 'ACTIVE', 'BLACKLISTED', 'DRAFT', name='sbcstatus'), nullable=True),
    sa.Column('ceo_name', sa.String(length=255), nullable=True),
    sa.Column('phone_1', sa.String(length=50), nullable=True),
    sa.Column('phone_2', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contract_ref', sa.String(length=100), nullable=True),
    sa.Column('has_contract_attachment', sa.Boolean(), nullable=True),
    sa.Column('contract_upload_date', sa.DateTime(), nullable=True),
    sa.Column('has_tax_regularization', sa.Boolean(), nullable=True),
    sa.Column('tax_reg_upload_date', sa.DateTime(), nullable=True),
    sa.Column('tax_reg_end_date', sa.Date(), nullable=True),
    sa.Column('rib', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sbcs_id'), 'sbcs', ['id'], unique=False)
    op.create_index(op.f('ix_sbcs_sbc_code'), 'sbcs', ['sbc_code'], unique=True)
    op.create_table('bon_de_commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bc_number', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sbc_id', sa.Integer(), nullable=False),
    sa.Column('total_amount_ht', sa.Float(), nullable=True),
    sa.Column('total_tax_amount', sa.Float(), nullable=True),
    sa.Column('total_amount_ttc', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PD_APPROVAL', 'CEO_APPROVAL', 'ACTIVE', 'BLACKLISTED', 'DRAFT', name='bcstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['internal_projects.id'], ),
    sa.ForeignKeyConstraint(['sbc_id'], ['sbcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bon_de_commandes_bc_number'), 'bon_de_commandes', ['bc_number'], unique=True)
    op.create_index(op.f('ix_bon_de_commandes_id'), 'bon_de_commandes', ['id'], unique=False)
    op.create_table('bc_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bc_id', sa.Integer(), nullable=False),
    sa.Column('merged_po_id', sa.Integer(), nullable=False),
    sa.Column('rate_sbc', sa.Float(), nullable=True),
    sa.Column('quantity_sbc', sa.Float(), nullable=True),
    sa.Column('unit_price_sbc', sa.Float(), nullable=True),
    sa.Column('line_amount_sbc', sa.Float(), nullable=True),
    sa.Column('applied_tax_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bc_id'], ['bon_de_commandes.id'], ),
    sa.ForeignKeyConstraint(['merged_po_id'], ['merged_pos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bc_items_id'), 'bc_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bc_items_id'), table_name='bc_items')
    op.drop_table('bc_items')
    op.drop_index(op.f('ix_bon_de_commandes_id'), table_name='bon_de_commandes')
    op.drop_index(op.f('ix_bon_de_commandes_bc_number'), table_name='bon_de_commandes')
    op.drop_table('bon_de_commandes')
    op.drop_index(op.f('ix_sbcs_sbc_code'), table_name='sbcs')
    op.drop_index(op.f('ix_sbcs_id'), table_name='sbcs')
    op.drop_table('sbcs')
    op.drop_index(op.f('ix_tax_rules_id'), table_name='tax_rules')
    op.drop_table('tax_rules')
    # ### end Alembic commands ###
