"""Refine project model and add account and customer tables

Revision ID: 309bd14b7adc
Revises: d3d43742747c
Create Date: 2025-11-06 20:25:12.577543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '309bd14b7adc'
down_revision: Union[str, Sequence[str], None] = 'd3d43742747c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=True)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=True)
    op.add_column('projects', sa.Column('project_type', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('has_extension_possibility', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('project_manager_name', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('forecast_plan_details', sa.String(length=1000), nullable=True))
    op.add_column('projects', sa.Column('budget_assigned', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('assignment_date', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('budget_period', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('account_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('direct_customer_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('final_customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'customers', ['final_customer_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'customers', ['direct_customer_id'], ['id'])
    op.drop_column('projects', 'project_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_manager', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'final_customer_id')
    op.drop_column('projects', 'direct_customer_id')
    op.drop_column('projects', 'account_id')
    op.drop_column('projects', 'budget_period')
    op.drop_column('projects', 'assignment_date')
    op.drop_column('projects', 'budget_assigned')
    op.drop_column('projects', 'forecast_plan_details')
    op.drop_column('projects', 'project_manager_name')
    op.drop_column('projects', 'has_extension_possibility')
    op.drop_column('projects', 'project_type')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
