"""MULTI Users Selection

Revision ID: 314b30a87fe0
Revises: ef031f790361
Create Date: 2026-03-03 16:56:53.907308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '314b30a87fe0'
down_revision: Union[str, Sequence[str], None] = 'ef031f790361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_primary_rel',
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['project_workflows.id'], ondelete='CASCADE')
    )
    op.drop_constraint(op.f('project_workflows_ibfk_1'), 'project_workflows', type_='foreignkey')
    op.drop_constraint(op.f('project_workflows_ibfk_2'), 'project_workflows', type_='foreignkey')
    op.create_foreign_key(None, 'project_workflows', 'internal_projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_workflows', 'primary_user_id')
    op.drop_constraint(op.f('workflow_support_rel_ibfk_2'), 'workflow_support_rel', type_='foreignkey')
    op.drop_constraint(op.f('workflow_support_rel_ibfk_1'), 'workflow_support_rel', type_='foreignkey')
    op.create_foreign_key(None, 'workflow_support_rel', 'project_workflows', ['workflow_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'workflow_support_rel', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_support_rel', type_='foreignkey')
    op.drop_constraint(None, 'workflow_support_rel', type_='foreignkey')
    op.create_foreign_key(op.f('workflow_support_rel_ibfk_1'), 'workflow_support_rel', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('workflow_support_rel_ibfk_2'), 'workflow_support_rel', 'project_workflows', ['workflow_id'], ['id'])
    op.add_column('project_workflows', sa.Column('primary_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'project_workflows', type_='foreignkey')
    op.create_foreign_key(op.f('project_workflows_ibfk_2'), 'project_workflows', 'internal_projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('project_workflows_ibfk_1'), 'project_workflows', 'users', ['primary_user_id'], ['id'])
    op.drop_table('workflow_primary_rel')
    # ### end Alembic commands ###
