"""Add ICE and RC to SBC

Revision ID: 328c078a575a
Revises: 229c335ab0b9
Create Date: 2026-01-06 16:18:49.253346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '328c078a575a'
down_revision: Union[str, Sequence[str], None] = '229c335ab0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sbcs', sa.Column('ice', sa.String(length=50), nullable=True))
    op.add_column('sbcs', sa.Column('rc', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sbcs', 'rc')
    op.drop_column('sbcs', 'ice')
    # ### end Alembic commands ###
