"""add_sbc_advances

Revision ID: 36864a72fb7e
Revises: 959a2a2731a6
Create Date: 2026-02-09 21:21:05.689242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36864a72fb7e'
down_revision: Union[str, Sequence[str], None] = '959a2a2731a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_requests', sa.Column('reception_attachment', sa.String(length=500), nullable=True))
    op.add_column('fund_requests', sa.Column('confirmed_reception_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund_requests', 'confirmed_reception_amount')
    op.drop_column('fund_requests', 'reception_attachment')
    # ### end Alembic commands ###
