"""cddcbh

Revision ID: 3b1b9ede59ce
Revises: b68dea8f617e
Create Date: 2025-12-29 17:25:43.472638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1b9ede59ce'
down_revision: Union[str, Sequence[str], None] = 'b68dea8f617e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('service_acceptances', sa.Column('file_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('service_acceptances', 'file_path')
    # ### end Alembic commands ###
