"""project and site link

Revision ID: 42b6eb9a345f
Revises: 6328b6305401
Create Date: 2025-11-17 11:36:18.067726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '42b6eb9a345f'
down_revision: Union[str, Sequence[str], None] = '6328b6305401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_code', sa.String(length=100), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_id'), 'sites', ['id'], unique=False)
    op.create_index(op.f('ix_sites_site_code'), 'sites', ['site_code'], unique=True)
    op.create_table('raw_purchase_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('due_qty', sa.Float(), nullable=True),
    sa.Column('po_status', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('line_amount', sa.Float(), nullable=True),
    sa.Column('billed_quantity', sa.Float(), nullable=True),
    sa.Column('po_no', sa.String(length=100), nullable=True),
    sa.Column('po_line_no', sa.Integer(), nullable=True),
    sa.Column('item_code', sa.String(length=100), nullable=True),
    sa.Column('item_description', sa.String(length=500), nullable=True),
    sa.Column('requested_qty', sa.Float(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('payment_terms_raw', sa.String(length=500), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_purchase_orders_customer_id'), 'raw_purchase_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_raw_purchase_orders_id'), 'raw_purchase_orders', ['id'], unique=False)
    op.create_index(op.f('ix_raw_purchase_orders_is_processed'), 'raw_purchase_orders', ['is_processed'], unique=False)
    op.create_index(op.f('ix_raw_purchase_orders_po_no'), 'raw_purchase_orders', ['po_no'], unique=False)
    op.create_index(op.f('ix_raw_purchase_orders_project_id'), 'raw_purchase_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_raw_purchase_orders_site_id'), 'raw_purchase_orders', ['site_id'], unique=False)
    op.drop_index(op.f('ix_purchase_orders_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_no'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_project_code'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_site_code'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    op.add_column('merged_pos', sa.Column('raw_po_id', sa.Integer(), nullable=True))
    op.add_column('merged_pos', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('merged_pos', sa.Column('site_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'merged_pos', ['raw_po_id'])
    op.create_foreign_key(None, 'merged_pos', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'merged_pos', 'raw_purchase_orders', ['raw_po_id'], ['id'])
    op.create_foreign_key(None, 'merged_pos', 'sites', ['site_id'], ['id'])
    op.drop_column('merged_pos', 'site_code')
    op.drop_column('merged_pos', 'project_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merged_pos', sa.Column('project_name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('merged_pos', sa.Column('site_code', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'merged_pos', type_='foreignkey')
    op.drop_constraint(None, 'merged_pos', type_='foreignkey')
    op.drop_constraint(None, 'merged_pos', type_='foreignkey')
    op.drop_constraint(None, 'merged_pos', type_='unique')
    op.drop_column('merged_pos', 'site_id')
    op.drop_column('merged_pos', 'project_id')
    op.drop_column('merged_pos', 'raw_po_id')
    op.create_table('purchase_orders',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('due_qty', mysql.FLOAT(), nullable=True),
    sa.Column('po_status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('unit_price', mysql.FLOAT(), nullable=True),
    sa.Column('line_amount', mysql.FLOAT(), nullable=True),
    sa.Column('billed_quantity', mysql.FLOAT(), nullable=True),
    sa.Column('po_no', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('po_line_no', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('item_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('requested_qty', mysql.FLOAT(), nullable=True),
    sa.Column('publish_date', mysql.DATETIME(), nullable=True),
    sa.Column('project_code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('payment_terms_raw', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('is_processed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('site_code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('item_description', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('uploaded_at', mysql.DATETIME(), nullable=True),
    sa.Column('uploader_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('purchase_orders_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_purchase_orders_site_code'), 'purchase_orders', ['site_code'], unique=False)
    op.create_index(op.f('ix_purchase_orders_project_code'), 'purchase_orders', ['project_code'], unique=False)
    op.create_index(op.f('ix_purchase_orders_po_no'), 'purchase_orders', ['po_no'], unique=False)
    op.create_index(op.f('ix_purchase_orders_id'), 'purchase_orders', ['id'], unique=False)
    op.drop_index(op.f('ix_raw_purchase_orders_site_id'), table_name='raw_purchase_orders')
    op.drop_index(op.f('ix_raw_purchase_orders_project_id'), table_name='raw_purchase_orders')
    op.drop_index(op.f('ix_raw_purchase_orders_po_no'), table_name='raw_purchase_orders')
    op.drop_index(op.f('ix_raw_purchase_orders_is_processed'), table_name='raw_purchase_orders')
    op.drop_index(op.f('ix_raw_purchase_orders_id'), table_name='raw_purchase_orders')
    op.drop_index(op.f('ix_raw_purchase_orders_customer_id'), table_name='raw_purchase_orders')
    op.drop_table('raw_purchase_orders')
    op.drop_index(op.f('ix_sites_site_code'), table_name='sites')
    op.drop_index(op.f('ix_sites_id'), table_name='sites')
    op.drop_table('sites')
    # ### end Alembic commands ###
