"""SBC -> USER

Revision ID: 44197dc77ad4
Revises: 43cd1353b762
Create Date: 2025-12-24 11:55:00.111642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44197dc77ad4'
down_revision: Union[str, Sequence[str], None] = '43cd1353b762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sbc_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'sbcs', ['sbc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'sbc_id')
    # ### end Alembic commands ###
