"""project and site linking

Revision ID: 4b6f7bd2f8ff
Revises: 6e0b41b15b0e
Create Date: 2025-11-17 13:36:15.208798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6f7bd2f8ff'
down_revision: Union[str, Sequence[str], None] = '6e0b41b15b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
