"""add_year_to_bc

Revision ID: 4c74ac546f21
Revises: 2d1702a2b1ed
Create Date: 2025-12-07 14:35:57.529883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c74ac546f21'
down_revision: Union[str, Sequence[str], None] = '2d1702a2b1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bon_de_commandes', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bon_de_commandes', 'year')
    # ### end Alembic commands ###
