"""Add site code to purchase_order table

Revision ID: 54df1ac6d1e1
Revises: 62798fd2e010
Create Date: 2025-11-05 11:50:35.984926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54df1ac6d1e1'
down_revision: Union[str, Sequence[str], None] = '62798fd2e010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('site_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_purchase_orders_site_code'), 'purchase_orders', ['site_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_orders_site_code'), table_name='purchase_orders')
    op.drop_column('purchase_orders', 'site_code')
    # ### end Alembic commands ###
