"""workflow_matrix_migration

Revision ID: 5c198094f3b5
Revises:
Create Date: 2026-03-12 13:08:48.932570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5c198094f3b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('expenses', 'act_id')
    op.execute("ALTER TABLE expenses DROP FOREIGN KEY expenses_ibfk_16;")

    op.drop_column('expenses', 'service_acceptance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('service_acceptance_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('act_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('expenses_ibfk_57'), 'expenses', 'service_acceptances', ['act_id'], ['id'])
    op.create_foreign_key(op.f('expenses_ibfk_15'), 'expenses', 'service_acceptances', ['service_acceptance_id'], ['id'])
    # ### end Alembic commands ###
