"""Add acceptance workflow columns to BCItem

Revision ID: 61b9c6998b5a
Revises: 835c9f9b62a2
Create Date: 2025-12-27 19:20:42.257325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '61b9c6998b5a'
down_revision: Union[str, Sequence[str], None] = '835c9f9b62a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bon_de_commandes', 'status',
               existing_type=mysql.ENUM('PENDING_L2', 'CEO_APPROVAL', 'ACTIVE', 'BLACKLISTED', 'DRAFT', 'APPROVED', 'SUBMITTED', 'REJECTED'),
               type_=sa.Enum('PENDING_L2', 'CEO_APPROVAL', 'ACTIVE', 'BLACKLISTED', 'DRAFT', 'APPROVED', 'REJECTED', 'SUBMITTED', name='bcstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bon_de_commandes', 'status',
               existing_type=sa.Enum('PENDING_L2', 'CEO_APPROVAL', 'ACTIVE', 'BLACKLISTED', 'DRAFT', 'APPROVED', 'REJECTED', 'SUBMITTED', name='bcstatus'),
               type_=mysql.ENUM('PENDING_L2', 'CEO_APPROVAL', 'ACTIVE', 'BLACKLISTED', 'DRAFT', 'APPROVED', 'SUBMITTED', 'REJECTED'),
               existing_nullable=True)
    # ### end Alembic commands ###
