"""Add new columns to merged_po and purchase_order tables

Revision ID: 62798fd2e010
Revises: 
Create Date: 2025-11-05 11:04:03.180795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '62798fd2e010'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merged_pos', sa.Column('po_id', sa.String(length=255), nullable=True))
    op.add_column('merged_pos', sa.Column('project_name', sa.String(length=255), nullable=True))
    op.add_column('merged_pos', sa.Column('site_code', sa.String(length=100), nullable=True))
    op.add_column('merged_pos', sa.Column('item_description', sa.String(length=500), nullable=True))
    op.add_column('merged_pos', sa.Column('payment_term', sa.String(length=100), nullable=True))
    op.add_column('merged_pos', sa.Column('internal_control', sa.Integer(), nullable=True))
    op.add_column('merged_pos', sa.Column('line_amount_hw', sa.Float(), nullable=True))
    op.create_index(op.f('ix_merged_pos_po_id'), 'merged_pos', ['po_id'], unique=True)
    op.create_index(op.f('ix_merged_pos_po_no'), 'merged_pos', ['po_no'], unique=False)
    op.drop_column('merged_pos', 'item_code')
    op.drop_column('merged_pos', 'billed_quantity')
    op.drop_column('merged_pos', 'po_status')
    op.drop_column('merged_pos', 'project_code')
    op.drop_column('merged_pos', 'due_qty')
    op.drop_column('merged_pos', 'line_amount')
    op.add_column('purchase_orders', sa.Column('payment_terms_raw', sa.String(length=500), nullable=True))
    op.add_column('purchase_orders', sa.Column('is_processed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_purchase_orders_po_no'), 'purchase_orders', ['po_no'], unique=False)
    op.create_index(op.f('ix_purchase_orders_project_code'), 'purchase_orders', ['project_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_orders_project_code'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_po_no'), table_name='purchase_orders')
    op.drop_column('purchase_orders', 'is_processed')
    op.drop_column('purchase_orders', 'payment_terms_raw')
    op.add_column('merged_pos', sa.Column('line_amount', mysql.FLOAT(), nullable=True))
    op.add_column('merged_pos', sa.Column('due_qty', mysql.FLOAT(), nullable=True))
    op.add_column('merged_pos', sa.Column('project_code', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('merged_pos', sa.Column('po_status', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('merged_pos', sa.Column('billed_quantity', mysql.FLOAT(), nullable=True))
    op.add_column('merged_pos', sa.Column('item_code', mysql.VARCHAR(length=100), nullable=True))
    op.drop_index(op.f('ix_merged_pos_po_no'), table_name='merged_pos')
    op.drop_index(op.f('ix_merged_pos_po_id'), table_name='merged_pos')
    op.drop_column('merged_pos', 'line_amount_hw')
    op.drop_column('merged_pos', 'internal_control')
    op.drop_column('merged_pos', 'payment_term')
    op.drop_column('merged_pos', 'item_description')
    op.drop_column('merged_pos', 'site_code')
    op.drop_column('merged_pos', 'project_name')
    op.drop_column('merged_pos', 'po_id')
    # ### end Alembic commands ###
