"""empty message

Revision ID: 6328b6305401
Revises: 2791e3b5e816
Create Date: 2025-11-14 11:50:32.268624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6328b6305401'
down_revision: Union[str, Sequence[str], None] = '2791e3b5e816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_orders', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.add_column('purchase_orders', sa.Column('uploader_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchase_orders', 'users', ['uploader_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_orders', type_='foreignkey')
    op.drop_column('purchase_orders', 'uploader_id')
    op.drop_column('purchase_orders', 'uploaded_at')
    # ### end Alembic commands ###
