"""Add columns

Revision ID: 66c1785dda6e
Revises: 3749ed4998ea
Create Date: 2026-01-28 17:07:12.313160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '66c1785dda6e'
down_revision: Union[str, Sequence[str], None] = '3749ed4998ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caisses', sa.Column('reserved_balance', sa.Float(), nullable=True))
    op.add_column('expenses', sa.Column('beneficiary_user_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('l1_approver_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('l1_at', sa.DateTime(), nullable=True))
    op.add_column('expenses', sa.Column('l2_approver_id', sa.Integer(), nullable=True))
    op.add_column('expenses', sa.Column('l2_at', sa.DateTime(), nullable=True))
    op.add_column('expenses', sa.Column('payment_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('expenses', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('expenses', sa.Column('signed_doc_url', sa.String(length=500), nullable=True))
    op.add_column('expenses', sa.Column('is_signed_copy_uploaded', sa.Boolean(), nullable=True))
    op.alter_column('expenses', 'amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('expenses', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('DRAFT', 'SUBMITTED', 'PENDING_L1', 'APPROVED_L1', 'PENDING_L2', 'APPROVED_L2', 'PAID', 'ACKNOWLEDGED', 'REJECTED', name='expensestatus'),
               existing_nullable=True)
    op.create_foreign_key(None, 'expenses', 'users', ['l1_approver_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'users', ['l2_approver_id'], ['id'])
    op.create_foreign_key(None, 'expenses', 'users', ['beneficiary_user_id'], ['id'])
    op.drop_column('expenses', 'approved_l2_at')
    op.drop_column('expenses', 'sbc_confirmation_date')
    op.drop_column('expenses', 'approved_l1_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('approved_l1_at', mysql.DATETIME(), nullable=True))
    op.add_column('expenses', sa.Column('sbc_confirmation_date', mysql.DATETIME(), nullable=True))
    op.add_column('expenses', sa.Column('approved_l2_at', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.alter_column('expenses', 'status',
               existing_type=sa.Enum('DRAFT', 'SUBMITTED', 'PENDING_L1', 'APPROVED_L1', 'PENDING_L2', 'APPROVED_L2', 'PAID', 'ACKNOWLEDGED', 'REJECTED', name='expensestatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('expenses', 'amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.drop_column('expenses', 'is_signed_copy_uploaded')
    op.drop_column('expenses', 'signed_doc_url')
    op.drop_column('expenses', 'acknowledged_at')
    op.drop_column('expenses', 'payment_confirmed_at')
    op.drop_column('expenses', 'l2_at')
    op.drop_column('expenses', 'l2_approver_id')
    op.drop_column('expenses', 'l1_at')
    op.drop_column('expenses', 'l1_approver_id')
    op.drop_column('expenses', 'beneficiary_user_id')
    op.drop_column('caisses', 'reserved_balance')
    # ### end Alembic commands ###
