"""Transaction PROOF

Revision ID: 6762c13149ab
Revises: f9a99ba23fb1
Create Date: 2026-02-26 14:16:33.634474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6762c13149ab'
down_revision: Union[str, Sequence[str], None] = 'f9a99ba23fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('l1_comment', sa.String(length=500), nullable=True))
    op.add_column('expenses', sa.Column('l2_comment', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'l2_comment')
    op.drop_column('expenses', 'l1_comment')
    # ### end Alembic commands ###
