"""Add Caisse System tables

Revision ID: 677b5109ad8f
Revises: 328c078a575a
Create Date: 2026-01-07 09:55:40.265036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677b5109ad8f'
down_revision: Union[str, Sequence[str], None] = '328c078a575a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caisses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_caisses_id'), 'caisses', ['id'], unique=False)
    op.create_table('fund_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_number', sa.String(length=50), nullable=True),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED_WAITING_FUNDS', 'COMPLETED', 'REJECTED', name='fundrequeststatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_requests_id'), 'fund_requests', ['id'], unique=False)
    op.create_index(op.f('ix_fund_requests_request_number'), 'fund_requests', ['request_number'], unique=True)
    op.create_table('fund_request_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('target_pm_id', sa.Integer(), nullable=False),
    sa.Column('requested_amount', sa.Float(), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['fund_requests.id'], ),
    sa.ForeignKeyConstraint(['target_pm_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fund_request_items_id'), 'fund_request_items', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caisse_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('CREDIT', 'DEBIT', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('related_request_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caisse_id'], ['caisses.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['related_request_id'], ['fund_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_fund_request_items_id'), table_name='fund_request_items')
    op.drop_table('fund_request_items')
    op.drop_index(op.f('ix_fund_requests_request_number'), table_name='fund_requests')
    op.drop_index(op.f('ix_fund_requests_id'), table_name='fund_requests')
    op.drop_table('fund_requests')
    op.drop_index(op.f('ix_caisses_id'), table_name='caisses')
    op.drop_table('caisses')
    # ### end Alembic commands ###
