"""Add other travelling costs

Revision ID: 690549c8bd5b
Revises: aba68a24fb79
Create Date: 2026-03-30 13:28:34.831628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '690549c8bd5b'
down_revision: Union[str, Sequence[str], None] = 'aba68a24fb79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('expenses_ibfk_64'), 'expenses', type_='foreignkey')
    # op.drop_column('expenses', 'service_acceptance_id')
    # op.drop_column('expenses', 'act_id')
    op.add_column('project_pnl', sa.Column('other_traveling_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_pnl', 'other_traveling_cost')
    # op.add_column('expenses', sa.Column('act_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # op.add_column('expenses', sa.Column('service_acceptance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # op.create_foreign_key(op.f('expenses_ibfk_64'), 'expenses', 'service_acceptances', ['service_acceptance_id'], ['id'])
    # ### end Alembic commands ###
