"""project and site linking

Revision ID: 6e0b41b15b0e
Revises: 21bbc02425f1
Create Date: 2025-11-17 12:58:49.700997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e0b41b15b0e'
down_revision: Union[str, Sequence[str], None] = '21bbc02425f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_purchase_orders', 'item_code')
    op.drop_column('raw_purchase_orders', 'due_qty')
    op.drop_column('raw_purchase_orders', 'billed_quantity')
    op.alter_column('sites', 'site_code',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.drop_column('sites', 'site_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sites', sa.Column('site_name', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('sites', 'site_code',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('raw_purchase_orders', sa.Column('billed_quantity', mysql.FLOAT(), nullable=True))
    op.add_column('raw_purchase_orders', sa.Column('due_qty', mysql.FLOAT(), nullable=True))
    op.add_column('raw_purchase_orders', sa.Column('item_code', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
