"""Add columns

Revision ID: 7362376bc7ed
Revises: 44197dc77ad4
Create Date: 2025-12-26 14:29:37.623914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7362376bc7ed'
down_revision: Union[str, Sequence[str], None] = '44197dc77ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merged_pos', sa.Column('assignment_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merged_pos', 'assignment_date')
    # ### end Alembic commands ###
