"""Add columns

Revision ID: 7404fbc86997
Revises: 07fff4f23ca8
Create Date: 2026-01-23 12:09:24.404875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7404fbc86997'
down_revision: Union[str, Sequence[str], None] = '07fff4f23ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('sbc_confirmation_date', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('expenses_ibfk_4'), 'expenses', type_='foreignkey')
    # op.drop_column('expenses', 'service_acceptance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('service_acceptance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('expenses_ibfk_4'), 'expenses', 'service_acceptances', ['service_acceptance_id'], ['id'])
    op.drop_column('expenses', 'sbc_confirmation_date')
    # ### end Alembic commands ###
