"""add_project_stakeholders

Revision ID: 745d63dcc430
Revises: 0fd2cb4a2da1
Create Date: 2026-03-01 03:00:38.016294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '745d63dcc430'
down_revision: Union[str, Sequence[str], None] = '0fd2cb4a2da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_stakeholders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('PD', 'PM', 'PC', 'RQC', 'SALES', name='projectroletype'), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['internal_projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', 'role', name='uix_proj_user_role')
    )
    op.create_index(op.f('ix_project_stakeholders_id'), 'project_stakeholders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_stakeholders_id'), table_name='project_stakeholders')
    op.drop_table('project_stakeholders')
    # ### end Alembic commands ###
