"""Add address and city to SBC

Revision ID: 7c939b2bc18e
Revises: 677b5109ad8f
Create Date: 2026-01-08 10:44:16.821861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c939b2bc18e'
down_revision: Union[str, Sequence[str], None] = '677b5109ad8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sbcs', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('sbcs', sa.Column('city', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sbcs', 'city')
    op.drop_column('sbcs', 'address')
    # ### end Alembic commands ###
