"""Add admin_note to FundRequestItem

Revision ID: 7ea9e48ec8be
Revises: 87df08abe171
Create Date: 2026-01-09 16:15:48.549084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea9e48ec8be'
down_revision: Union[str, Sequence[str], None] = '87df08abe171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_request_items', sa.Column('admin_note', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund_request_items', 'admin_note')
    # ### end Alembic commands ###
