"""ACC

Revision ID: 835c9f9b62a2
Revises: 7362376bc7ed
Create Date: 2025-12-27 14:05:04.555202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835c9f9b62a2'
down_revision: Union[str, Sequence[str], None] = '7362376bc7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bc_items', sa.Column('qc_validation_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='validationstate'), nullable=True))
    op.add_column('bc_items', sa.Column('pm_validation_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='validationstate'), nullable=True))
    op.add_column('bc_items', sa.Column('global_status', sa.Enum('OPEN', 'POSTPONED', 'READY_FOR_ACT', 'ACCEPTED', 'PERMANENTLY_REJECTED', name='itemglobalstatus'), nullable=True))
    op.add_column('bc_items', sa.Column('rejection_count', sa.Integer(), nullable=True))
    op.add_column('bc_items', sa.Column('postponed_until', sa.DateTime(), nullable=True))
    op.add_column('bc_items', sa.Column('act_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bc_items', 'service_acceptances', ['act_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bc_items', type_='foreignkey')
    op.drop_column('bc_items', 'act_id')
    op.drop_column('bc_items', 'postponed_until')
    op.drop_column('bc_items', 'rejection_count')
    op.drop_column('bc_items', 'global_status')
    op.drop_column('bc_items', 'pm_validation_status')
    op.drop_column('bc_items', 'qc_validation_status')
    # ### end Alembic commands ###
