"""EXP column in transaction

Revision ID: w
Revises: a9c7a324dfb5
Create Date: 2026-03-11 11:41:17.437289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '83fc8c952f7a'
down_revision: Union[str, Sequence[str], None] = 'a9c7a324dfb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('expenses_ibfk_46'), 'expenses', type_='foreignkey')
    # op.drop_constraint(op.f('expenses_ibfk_45'), 'expenses', type_='foreignkey')
    # op.drop_column('expenses', 'act_id')
    # op.drop_column('expenses', 'service_acceptance_id')
    op.add_column('transactions', sa.Column('expense_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'expenses', ['expense_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'expense_id')
    op.add_column('expenses', sa.Column('service_acceptance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('act_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('expenses_ibfk_45'), 'expenses', 'service_acceptances', ['service_acceptance_id'], ['id'])
    op.create_foreign_key(op.f('expenses_ibfk_46'), 'expenses', 'service_acceptances', ['act_id'], ['id'])
    # ### end Alembic commands ###
