"""Add other_service_cost

Revision ID: 853b3707850e
Revises: 2e1d189f0f54
Create Date: 2026-03-27 23:35:07.975175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '853b3707850e'
down_revision: Union[str, Sequence[str], None] = '2e1d189f0f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('expenses_ibfk_54'), 'expenses', type_='foreignkey')
    # op.drop_column('expenses', 'service_acceptance_id')
    # op.drop_column('expenses', 'act_id')
    op.add_column('project_pnl', sa.Column('other_service_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_pnl', 'other_service_cost')
    # op.add_column('expenses', sa.Column('act_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # op.add_column('expenses', sa.Column('service_acceptance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # op.create_foreign_key(op.f('expenses_ibfk_54'), 'expenses', 'service_acceptances', ['service_acceptance_id'], ['id'])
    # ### end Alembic commands ###
