"""Add columns

Revision ID: 85b27148313d
Revises: 66c1785dda6e
Create Date: 2026-01-31 02:20:59.041086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '85b27148313d'
down_revision: Union[str, Sequence[str], None] = '66c1785dda6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expenses_ibfk_2'), 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'act_id')
    op.add_column('service_acceptances', sa.Column('expense_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'service_acceptances', 'expenses', ['expense_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_acceptances', type_='foreignkey')
    op.drop_column('service_acceptances', 'expense_id')
    op.add_column('expenses', sa.Column('act_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('expenses_ibfk_2'), 'expenses', 'service_acceptances', ['act_id'], ['id'])
    # ### end Alembic commands ###
