"""Widen fund_requests status column

Revision ID: 87df08abe171
Revises: d2c58e893b2a
Create Date: 2026-01-09 12:01:51.479476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87df08abe171'
down_revision: Union[str, Sequence[str], None] = 'd2c58e893b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fund_requests', 'status',
               existing_type=mysql.ENUM('PENDING_APPROVAL', 'APPROVED_WAITING_FUNDS', 'COMPLETED', 'REJECTED'),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fund_requests', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('PENDING_APPROVAL', 'APPROVED_WAITING_FUNDS', 'COMPLETED', 'REJECTED'),
               existing_nullable=True)
    # ### end Alembic commands ###
