"""add_sbc_advances

Revision ID: 959a2a2731a6
Revises: cefde9e891d4
Create Date: 2026-02-08 19:36:31.699369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959a2a2731a6'
down_revision: Union[str, Sequence[str], None] = 'cefde9e891d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('bc_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'bc_items', ['bc_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'bc_item_id')
    # ### end Alembic commands ###
