"""Initial database schema

Revision ID: 99e62e80d215
Revises: 
Create Date: 2025-12-15 17:30:49.902753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '99e62e80d215'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ajoute les 4 nouvelles colonnes
    op.add_column('user_performance_targets', sa.Column('po_master_plan', sa.Float(), nullable=True))
    op.add_column('user_performance_targets', sa.Column('po_monthly_update', sa.Float(), nullable=True))
    op.add_column('user_performance_targets', sa.Column('acceptance_master_plan', sa.Float(), nullable=True))
    op.add_column('user_performance_targets', sa.Column('acceptance_monthly_update', sa.Float(), nullable=True))
    
    # Supprime les 2 anciennes colonnes
    op.drop_column('user_performance_targets', 'target_po_amount')
    op.drop_column('user_performance_targets', 'target_invoice_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Fait l'inverse pour pouvoir annuler la migration
    op.add_column('user_performance_targets', sa.Column('target_invoice_amount', sa.Float(), nullable=True))
    op.add_column('user_performance_targets', sa.Column('target_po_amount', sa.Float(), nullable=True))
    op.drop_column('user_performance_targets', 'acceptance_monthly_update')
    op.drop_column('user_performance_targets', 'acceptance_master_plan')
    op.drop_column('user_performance_targets', 'po_monthly_update')
    op.drop_column('user_performance_targets', 'po_master_plan')
    # ### end Alembic commands ###

