"""Initial database schema

Revision ID: 99e62e80d215
Revises: 
Create Date: 2025-12-15 17:30:49.902753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '99e62e80d215'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bon_de_commandes', sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    op.add_column('bon_de_commandes', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('bon_de_commandes', sa.Column('approver_l1_id', sa.Integer(), nullable=True))
    op.add_column('bon_de_commandes', sa.Column('approved_l1_at', sa.DateTime(), nullable=True))
    op.add_column('bon_de_commandes', sa.Column('approver_l2_id', sa.Integer(), nullable=True))
    op.add_column('bon_de_commandes', sa.Column('approved_l2_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'bon_de_commandes', 'users', ['approver_l2_id'], ['id'])
    op.create_foreign_key(None, 'bon_de_commandes', 'users', ['approver_l1_id'], ['id'])
    op.create_index(op.f('ix_sbcs_email'), 'sbcs', ['email'], unique=True)
    op.create_unique_constraint(None, 'sbcs', ['phone_1'])
    op.add_column('user_performance_targets', sa.Column('po_master_plan', sa.Float(), nullable=True))
    op.add_column('user_performance_targets', sa.Column('po_monthly_update', sa.Float(), nullable=True))
    op.add_column('user_performance_targets', sa.Column('acceptance_master_plan', sa.Float(), nullable=True))
    op.add_column('user_performance_targets', sa.Column('acceptance_monthly_update', sa.Float(), nullable=True))
    op.drop_column('user_performance_targets', 'target_po_amount')
    op.drop_column('user_performance_targets', 'target_invoice_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_performance_targets', sa.Column('target_invoice_amount', mysql.FLOAT(), nullable=True))
    op.add_column('user_performance_targets', sa.Column('target_po_amount', mysql.FLOAT(), nullable=True))
    op.drop_column('user_performance_targets', 'acceptance_monthly_update')
    op.drop_column('user_performance_targets', 'acceptance_master_plan')
    op.drop_column('user_performance_targets', 'po_monthly_update')
    op.drop_column('user_performance_targets', 'po_master_plan')
    op.drop_constraint(None, 'sbcs', type_='unique')
    op.drop_index(op.f('ix_sbcs_email'), table_name='sbcs')
    op.drop_constraint(None, 'bon_de_commandes', type_='foreignkey')
    op.drop_constraint(None, 'bon_de_commandes', type_='foreignkey')
    op.drop_column('bon_de_commandes', 'approved_l2_at')
    op.drop_column('bon_de_commandes', 'approver_l2_id')
    op.drop_column('bon_de_commandes', 'approved_l1_at')
    op.drop_column('bon_de_commandes', 'approver_l1_id')
    op.drop_column('bon_de_commandes', 'submitted_at')
    op.drop_column('bon_de_commandes', 'rejection_reason')
    # ### end Alembic commands ###
