"""Add Huawei DR2 PnL engine models

Revision ID: 9a4c44653bbb
Revises: 83fc8c952f7a
Create Date: 2026-03-26 15:04:54.389252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a4c44653bbb'
down_revision: Union[str, Sequence[str], None] = '83fc8c952f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnl_field_ops_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('tl_name', sa.String(length=255), nullable=False),
    sa.Column('car_allocation', sa.Float(), nullable=True),
    sa.Column('fuel_cost', sa.Float(), nullable=True),
    sa.Column('jawaz_cost', sa.Float(), nullable=True),
    sa.Column('ehs_tools', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pnl_field_ops_costs_id'), 'pnl_field_ops_costs', ['id'], unique=False)
    op.create_index(op.f('ix_pnl_field_ops_costs_period'), 'pnl_field_ops_costs', ['period'], unique=False)
    op.create_table('pnl_backoffice_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('entered_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pnl_backoffice_expenses_id'), 'pnl_backoffice_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_pnl_backoffice_expenses_period'), 'pnl_backoffice_expenses', ['period'], unique=False)
    op.create_table('pnl_labor_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('employee_name', sa.String(length=255), nullable=False),
    sa.Column('role_type', sa.String(length=50), nullable=True),
    sa.Column('tjm', sa.Float(), nullable=True),
    sa.Column('java_validated_days', sa.Float(), nullable=True),
    sa.Column('allocated_days', sa.Float(), nullable=True),
    sa.Column('internal_project_id', sa.Integer(), nullable=True),
    sa.Column('allocated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['allocated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['internal_project_id'], ['internal_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pnl_labor_allocations_id'), 'pnl_labor_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_pnl_labor_allocations_internal_project_id'), 'pnl_labor_allocations', ['internal_project_id'], unique=False)
    op.create_index(op.f('ix_pnl_labor_allocations_period'), 'pnl_labor_allocations', ['period'], unique=False)
    op.create_table('project_pnl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('internal_project_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'PUBLISHED', 'REJECTED', name='pnlstatus'), nullable=True),
    sa.Column('service_revenue', sa.Float(), nullable=True),
    sa.Column('equipment_revenue', sa.Float(), nullable=True),
    sa.Column('equipment_cost', sa.Float(), nullable=True),
    sa.Column('labor_cost_field', sa.Float(), nullable=True),
    sa.Column('labor_cost_mgmt', sa.Float(), nullable=True),
    sa.Column('coop_cost_entreprise', sa.Float(), nullable=True),
    sa.Column('coop_cost_pp', sa.Float(), nullable=True),
    sa.Column('travel_cost', sa.Float(), nullable=True),
    sa.Column('other_service_cost', sa.Float(), nullable=True),
    sa.Column('car_allocation_cost', sa.Float(), nullable=True),
    sa.Column('fuel_cost', sa.Float(), nullable=True),
    sa.Column('jawaz_cost', sa.Float(), nullable=True),
    sa.Column('ehs_cost', sa.Float(), nullable=True),
    sa.Column('period_costs', sa.Float(), nullable=True),
    sa.Column('risk_reserve', sa.Float(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['internal_project_id'], ['internal_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_pnl_id'), 'project_pnl', ['id'], unique=False)
    op.create_index(op.f('ix_project_pnl_internal_project_id'), 'project_pnl', ['internal_project_id'], unique=False)
    op.create_index(op.f('ix_project_pnl_period'), 'project_pnl', ['period'], unique=False)
    # op.drop_constraint(op.f('expenses_ibfk_57'), 'expenses', type_='foreignkey')
    # op.drop_constraint(op.f('expenses_ibfk_66'), 'expenses', type_='foreignkey')
    # op.drop_column('expenses', 'act_id')
    # op.drop_column('expenses', 'service_acceptance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('service_acceptance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # op.add_column('expenses', sa.Column('act_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('expenses_ibfk_66'), 'expenses', 'service_acceptances', ['service_acceptance_id'], ['id'])
    op.create_foreign_key(op.f('expenses_ibfk_57'), 'expenses', 'service_acceptances', ['act_id'], ['id'])
    op.drop_index(op.f('ix_project_pnl_period'), table_name='project_pnl')
    op.drop_index(op.f('ix_project_pnl_internal_project_id'), table_name='project_pnl')
    op.drop_index(op.f('ix_project_pnl_id'), table_name='project_pnl')
    op.drop_table('project_pnl')
    op.drop_index(op.f('ix_pnl_labor_allocations_period'), table_name='pnl_labor_allocations')
    op.drop_index(op.f('ix_pnl_labor_allocations_internal_project_id'), table_name='pnl_labor_allocations')
    op.drop_index(op.f('ix_pnl_labor_allocations_id'), table_name='pnl_labor_allocations')
    op.drop_table('pnl_labor_allocations')
    op.drop_index(op.f('ix_pnl_backoffice_expenses_period'), table_name='pnl_backoffice_expenses')
    op.drop_index(op.f('ix_pnl_backoffice_expenses_id'), table_name='pnl_backoffice_expenses')
    op.drop_table('pnl_backoffice_expenses')
    op.drop_index(op.f('ix_pnl_field_ops_costs_period'), table_name='pnl_field_ops_costs')
    op.drop_index(op.f('ix_pnl_field_ops_costs_id'), table_name='pnl_field_ops_costs')
    op.drop_table('pnl_field_ops_costs')
    # ### end Alembic commands ###
