"""add_performance_targets

Revision ID: 9dc18d775e58
Revises: cd9d19e1ada2
Create Date: 2025-11-29 14:47:34.070636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc18d775e58'
down_revision: Union[str, Sequence[str], None] = 'cd9d19e1ada2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_performance_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('target_po_amount', sa.Float(), nullable=True),
    sa.Column('target_invoice_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uix_user_year_month')
    )
    op.create_index(op.f('ix_user_performance_targets_id'), 'user_performance_targets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_performance_targets_id'), table_name='user_performance_targets')
    op.drop_table('user_performance_targets')
    # ### end Alembic commands ###
