"""add_sbc_advances

Revision ID: a9ac30fd2252
Revises: 36864a72fb7e
Create Date: 2026-02-09 22:19:47.563001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ac30fd2252'
down_revision: Union[str, Sequence[str], None] = '36864a72fb7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_request_items', sa.Column('confirmed_amount', sa.Float(), nullable=True))
    op.add_column('fund_requests', sa.Column('variance_note', sa.Text(), nullable=True))
    op.add_column('fund_requests', sa.Column('variance_acknowledged', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund_requests', 'variance_acknowledged')
    op.drop_column('fund_requests', 'variance_note')
    op.drop_column('fund_request_items', 'confirmed_amount')
    # ### end Alembic commands ###
