"""drop project_stakeholders table

Revision ID: a9c7a324dfb5
Revises: 3473b6b846e1
Create Date: 2026-03-09 12:28:38.261291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9c7a324dfb5'
down_revision: Union[str, Sequence[str], None] = '3473b6b846e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- FIX: Use Raw SQL to force the drop ---
    op.execute('SET FOREIGN_KEY_CHECKS = 0;')
    op.execute('DROP TABLE IF EXISTS `project_stakeholders`;')
    op.execute('SET FOREIGN_KEY_CHECKS = 1;')
    # -------------------------------------------

    # Remove the old Alembic commands for dropping
    # op.drop_index(op.f('uix_proj_user_role'), table_name='project_stakeholders')
    # op.drop_table('project_stakeholders')

    # Continue with the rest of your upgrade logic...
    op.add_column('bon_de_commandes', sa.Column('l1_approval_comment', sa.Text(), nullable=True))
    op.add_column('bon_de_commandes', sa.Column('l2_approval_comment', sa.Text(), nullable=True))
    
    # --- DANGER: Comment these out for safety unless you are sure you want to delete these columns ---
    # op.drop_constraint(op.f('expenses_ibfk_46'), 'expenses', type_='foreignkey')
    # op.drop_constraint(op.f('expenses_ibfk_14'), 'expenses', type_='foreignkey')
    # op.drop_column('expenses', 'service_acceptance_id')
    # op.drop_column('expenses', 'act_id')
    
    op.alter_column('project_workflows', 'action_type',
               existing_type=mysql.ENUM('BC_CREATE_DRAFT', 'BC_SUBMIT', 'BC_APPROVE_L1', 'BC_APPROVE_L2', 'BC_CONFIRM', 'BC_GENERATE', 'ACT_APPROVE_RQC', 'ACT_APPROVE_PM', 'ACT_APPROVE_PD', 'ACT_GENERATE', 'FUND_CREATE', 'FUND_APPROVE', 'FUND_CONFIRM', 'FUND_UPLOAD_DOC', 'EXP_CREATE_DRAFT', 'EXP_SUBMIT', 'EXP_APPROVE_L1', 'EXP_APPROVE_L2', 'ROLE_PM', 'ROLE_PD', 'ROLE_Pc'),
               type_=sa.Enum('ROLE_PD', 'ROLE_PM', 'ROLE_PC', 'ROLE_RQC', 'ROLE_SALES', 'BC_CREATE_DRAFT', 'BC_SUBMIT', 'BC_APPROVE_L1', 'BC_APPROVE_L2', 'BC_GENERATE', 'FUND_CREATE', 'FUND_APPROVE', 'FUND_CONFIRM', 'EXP_CREATE_DRAFT', 'EXP_SUBMIT', 'EXP_APPROVE_L1', 'EXP_APPROVE_L2', 'ACT_APPROVE_RQC', 'ACT_APPROVE_PM', 'ACT_APPROVE_PD', 'ACT_GENERATE', name='projectactiontype'),
               existing_nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_workflows', 'action_type',
               existing_type=sa.Enum('ROLE_PD', 'ROLE_PM', 'ROLE_PC', 'ROLE_RQC', 'ROLE_SALES', 'BC_CREATE_DRAFT', 'BC_SUBMIT', 'BC_APPROVE_L1', 'BC_APPROVE_L2', 'BC_GENERATE', 'FUND_CREATE', 'FUND_APPROVE', 'FUND_CONFIRM', 'EXP_CREATE_DRAFT', 'EXP_SUBMIT', 'EXP_APPROVE_L1', 'EXP_APPROVE_L2', 'ACT_APPROVE_RQC', 'ACT_APPROVE_PM', 'ACT_APPROVE_PD', 'ACT_GENERATE', name='projectactiontype'),
               type_=mysql.ENUM('BC_CREATE_DRAFT', 'BC_SUBMIT', 'BC_APPROVE_L1', 'BC_APPROVE_L2', 'BC_CONFIRM', 'BC_GENERATE', 'ACT_APPROVE_RQC', 'ACT_APPROVE_PM', 'ACT_APPROVE_PD', 'ACT_GENERATE', 'FUND_CREATE', 'FUND_APPROVE', 'FUND_CONFIRM', 'FUND_UPLOAD_DOC', 'EXP_CREATE_DRAFT', 'EXP_SUBMIT', 'EXP_APPROVE_L1', 'EXP_APPROVE_L2', 'ROLE_PM', 'ROLE_PD', 'ROLE_Pc'),
               existing_nullable=False)
    op.add_column('expenses', sa.Column('act_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('service_acceptance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('expenses_ibfk_14'), 'expenses', 'service_acceptances', ['service_acceptance_id'], ['id'])
    op.create_foreign_key(op.f('expenses_ibfk_46'), 'expenses', 'service_acceptances', ['act_id'], ['id'])
    op.drop_column('bon_de_commandes', 'l2_approval_comment')
    op.drop_column('bon_de_commandes', 'l1_approval_comment')
    op.create_table('project_stakeholders',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('role', mysql.ENUM('PD', 'PM', 'PC', 'RQC', 'SALES'), nullable=False),
    sa.Column('is_lead', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['internal_projects.id'], name=op.f('project_stakeholders_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('project_stakeholders_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uix_proj_user_role'), 'project_stakeholders', ['project_id', 'user_id', 'role'], unique=True)
    try:
        op.create_foreign_key(
            'some_other_table_ibfk_1', # The constraint name
            'some_other_table',       # The table that has the foreign key
            'project_stakeholders',   # The table it points to
            ['the_column_name'],      # The column name in 'some_other_table'
            ['id']                    # The column it points to in 'project_stakeholders'
        )
    except Exception as e:
        print(f"Could not re-create constraint: {e}")
    # ### end Alembic commands ###
