"""Add start and end dates to LaborAllocation

Revision ID: aba68a24fb79
Revises: 853b3707850e
Create Date: 2026-03-28 18:30:17.119998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aba68a24fb79'
down_revision: Union[str, Sequence[str], None] = '853b3707850e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('expenses_ibfk_42'), 'expenses', type_='foreignkey')
    # op.drop_column('expenses', 'act_id')
    # op.drop_column('expenses', 'service_acceptance_id')
    op.add_column('pnl_labor_allocations', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('pnl_labor_allocations', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pnl_labor_allocations', 'end_date')
    op.drop_column('pnl_labor_allocations', 'start_date')
    # op.add_column('expenses', sa.Column('service_acceptance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # op.add_column('expenses', sa.Column('act_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # op.create_foreign_key(op.f('expenses_ibfk_42'), 'expenses', 'service_acceptances', ['service_acceptance_id'], ['id'])
    # ### end Alembic commands ###
