"""Link project manager to user table and add project type enum

Revision ID: aeff0d281ab1
Revises: 309bd14b7adc
Create Date: 2025-11-06 20:44:06.454514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aeff0d281ab1'
down_revision: Union[str, Sequence[str], None] = '309bd14b7adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_manager_id', sa.Integer(), nullable=True))
    op.alter_column('projects', 'project_type',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Enum('INTERNAL', 'CUSTOMER_FIXED_PRICE', 'CUSTOMER_TIME_MATERIAL', name='projecttype'),
               existing_nullable=True)
    op.create_foreign_key(None, 'projects', 'users', ['project_manager_id'], ['id'])
    op.drop_column('projects', 'project_manager_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_manager_name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'project_type',
               existing_type=sa.Enum('INTERNAL', 'CUSTOMER_FIXED_PRICE', 'CUSTOMER_TIME_MATERIAL', name='projecttype'),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('projects', 'project_manager_id')
    # ### end Alembic commands ###
