"""Fix circular dependency in User-BonDeCommande relationship

Revision ID: b0324b406b8b
Revises: 1a2a7cd9d778
Create Date: 2025-12-22 12:28:33.981981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0324b406b8b'
down_revision: Union[str, Sequence[str], None] = '1a2a7cd9d778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
