"""Add columns

Revision ID: b8e53050d9cc
Revises: ef733b89512b
Create Date: 2026-01-20 12:31:04.842556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b8e53050d9cc'
down_revision: Union[str, Sequence[str], None] = 'ef733b89512b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expenses_ibfk_3'), 'expenses', type_='foreignkey')
    # op.drop_column('expenses', 'service_acceptance_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('service_acceptance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('expenses_ibfk_3'), 'expenses', 'service_acceptances', ['service_acceptance_id'], ['id'])
    # ### end Alembic commands ###
