"""cdcdc

Revision ID: bc9213c9ef4a
Revises: f912ad1427ac
Create Date: 2025-12-30 16:26:54.616874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9213c9ef4a'
down_revision: Union[str, Sequence[str], None] = 'f912ad1427ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_acceptances', sa.Column('applied_tax_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_acceptances', 'applied_tax_rate')
    # ### end Alembic commands ###
