"""auto priority

Revision ID: cd9d19e1ada2
Revises: 9b3fe32c3034
Create Date: 2025-11-28 09:44:58.797432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cd9d19e1ada2'
down_revision: Union[str, Sequence[str], None] = '9b3fe32c3034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_assignment_rules_priority'), table_name='site_assignment_rules')
    op.drop_column('site_assignment_rules', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_assignment_rules', sa.Column('priority', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_site_assignment_rules_priority'), 'site_assignment_rules', ['priority'], unique=False)
    # ### end Alembic commands ###
