"""Add sbc_type to SBC and link User to SBC

Revision ID: ce6263ad171c
Revises: bc9213c9ef4a
Create Date: 2026-01-02 12:24:34.953002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6263ad171c'
down_revision: Union[str, Sequence[str], None] = 'bc9213c9ef4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sbcs', sa.Column('sbc_type', sa.Enum('PP', 'ENTREPRISE', name='sbctype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sbcs', 'sbc_type')
    # ### end Alembic commands ###
