"""add_sbc_advances

Revision ID: cefde9e891d4
Revises: 0ee017f7eb1e
Create Date: 2026-02-07 22:54:07.189371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cefde9e891d4'
down_revision: Union[str, Sequence[str], None] = '0ee017f7eb1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('sbc_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expenses', 'sbcs', ['sbc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'sbc_id')
    # ### end Alembic commands ###
