"""empty message

Revision ID: d2c58e893b2a
Revises: 7c939b2bc18e
Create Date: 2026-01-09 11:01:10.853277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c58e893b2a'
down_revision: Union[str, Sequence[str], None] = '7c939b2bc18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_request_items', sa.Column('remarque', sa.String(length=255), nullable=True))
    op.add_column('fund_requests', sa.Column('paid_amount', sa.Float(), nullable=True))
    op.add_column('fund_requests', sa.Column('admin_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund_requests', 'admin_comment')
    op.drop_column('fund_requests', 'paid_amount')
    op.drop_column('fund_request_items', 'remarque')
    # ### end Alembic commands ###
