"""create_unified_workflow_tables

Revision ID: ef031f790361
Revises: 8ebce2dd03b0
Create Date: 2026-03-03 14:54:35.328194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef031f790361'
down_revision: Union[str, Sequence[str], None] = '8ebce2dd03b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_workflows', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_workflows', 'created_at')
    # ### end Alembic commands ###
