"""Replace act_id with service_acceptance_id in expenses

Revision ID: ef733b89512b
Revises: 146d208d5fe9
Create Date: 2026-01-15 09:37:12.174168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ef733b89512b'
down_revision: Union[str, Sequence[str], None] = '146d208d5fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('expenses', sa.Column('service_acceptance_id', sa.Integer(), nullable=True))
    op.alter_column('expenses', 'project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('expenses', 'exp_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('expenses', 'beneficiary',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('expenses', 'amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('expenses', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('expenses', 'requester_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('expenses', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('expenses', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # op.drop_constraint(op.f('fk_expenses_act'), 'expenses', type_='foreignkey')
    op.create_foreign_key(None, 'expenses', 'service_acceptances', ['service_acceptance_id'], ['id'])
    # op.drop_column('expenses', 'approved_l2_by')
    op.drop_column('expenses', 'act_id')
    op.drop_column('expenses', 'approved_l2_at')
    op.drop_column('expenses', 'rejection_reason')
    op.drop_column('expenses', 'approved_l1_by')
    op.drop_column('expenses', 'approved_l1_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('approved_l1_at', mysql.DATETIME(), nullable=True))
    op.add_column('expenses', sa.Column('approved_l1_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('rejection_reason', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('expenses', sa.Column('approved_l2_at', mysql.DATETIME(), nullable=True))
    op.add_column('expenses', sa.Column('act_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column('approved_l2_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.create_foreign_key(op.f('fk_expenses_act'), 'expenses', 'service_acceptances', ['act_id'], ['id'])
    op.alter_column('expenses', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('expenses', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('expenses', 'requester_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('expenses', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('expenses', 'amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('expenses', 'beneficiary',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('expenses', 'exp_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('expenses', 'project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('expenses', 'service_acceptance_id')
    # ### end Alembic commands ###
