"""Add relationships for BC creator and approvers

Revision ID: f19fdfe602a6
Revises: 1a2a7cd9d778
Create Date: 2025-12-22 12:10:38.924855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f19fdfe602a6'
down_revision: Union[str, Sequence[str], None] = '1a2a7cd9d778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bon_de_commandes', sa.Column('bc_type', sa.Enum('STANDARD', 'PERSONNE_PHYSIQUE', name='bctype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bon_de_commandes', 'bc_type')
    # ### end Alembic commands ###
