"""cdcdc

Revision ID: f912ad1427ac
Revises: 3b1b9ede59ce
Create Date: 2025-12-30 16:01:00.330844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f912ad1427ac'
down_revision: Union[str, Sequence[str], None] = '3b1b9ede59ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_acceptances', sa.Column('total_amount_ht', sa.Float(), nullable=True))
    op.add_column('service_acceptances', sa.Column('total_tax_amount', sa.Float(), nullable=True))
    op.add_column('service_acceptances', sa.Column('total_amount_ttc', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_acceptances', 'total_amount_ttc')
    op.drop_column('service_acceptances', 'total_tax_amount')
    op.drop_column('service_acceptances', 'total_amount_ht')
    # ### end Alembic commands ###
