"""add_merged_po_editable_columns_and_changelog

Revision ID: fb8336c7b8d0
Revises: c3d4e5f6a7b8
Create Date: 2026-04-10 23:56:08.802880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb8336c7b8d0'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merged_po_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merged_po_id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.String(length=255), nullable=False),
    sa.Column('site_code', sa.String(length=100), nullable=True),
    sa.Column('item_description', sa.String(length=500), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['merged_po_id'], ['merged_pos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merged_po_change_logs_changed_at'), 'merged_po_change_logs', ['changed_at'], unique=False)
    op.create_index(op.f('ix_merged_po_change_logs_id'), 'merged_po_change_logs', ['id'], unique=False)
    op.create_index(op.f('ix_merged_po_change_logs_merged_po_id'), 'merged_po_change_logs', ['merged_po_id'], unique=False)
    op.create_index(op.f('ix_merged_po_change_logs_po_id'), 'merged_po_change_logs', ['po_id'], unique=False)
    op.add_column('merged_pos', sa.Column('status_installation', sa.String(length=100), nullable=True))
    op.add_column('merged_pos', sa.Column('date_installation', sa.Date(), nullable=True))
    op.add_column('merged_pos', sa.Column('need_document', sa.String(length=10), nullable=True))
    op.add_column('merged_pos', sa.Column('date_document_ok', sa.Date(), nullable=True))
    op.add_column('merged_pos', sa.Column('remark_last_remark', sa.Text(), nullable=True))
    op.add_column('merged_pos', sa.Column('readiness_acceptance', sa.String(length=100), nullable=True))
    op.add_column('merged_pos', sa.Column('rejection_remark', sa.Text(), nullable=True))
    op.add_column('merged_pos', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('merged_pos', sa.Column('status_report_isdp', sa.String(length=50), nullable=True))
    op.add_column('merged_pos', sa.Column('date_close_report_isdp', sa.Date(), nullable=True))
    op.add_column('merged_pos', sa.Column('remark_qc_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merged_pos', 'remark_qc_reason')
    op.drop_column('merged_pos', 'date_close_report_isdp')
    op.drop_column('merged_pos', 'status_report_isdp')
    op.drop_column('merged_pos', 'remarks')
    op.drop_column('merged_pos', 'rejection_remark')
    op.drop_column('merged_pos', 'readiness_acceptance')
    op.drop_column('merged_pos', 'remark_last_remark')
    op.drop_column('merged_pos', 'date_document_ok')
    op.drop_column('merged_pos', 'need_document')
    op.drop_column('merged_pos', 'date_installation')
    op.drop_column('merged_pos', 'status_installation')
    op.drop_index(op.f('ix_merged_po_change_logs_po_id'), table_name='merged_po_change_logs')
    op.drop_index(op.f('ix_merged_po_change_logs_merged_po_id'), table_name='merged_po_change_logs')
    op.drop_index(op.f('ix_merged_po_change_logs_id'), table_name='merged_po_change_logs')
    op.drop_index(op.f('ix_merged_po_change_logs_changed_at'), table_name='merged_po_change_logs')
    op.drop_table('merged_po_change_logs')
    # ### end Alembic commands ###
