"""add_merged_po_editable_columns_and_changelog

Revision ID: fb8336c7b8d0
Revises: c3d4e5f6a7b8
Create Date: 2026-04-10 23:56:08.802880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fb8336c7b8d0'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _col_exists(conn, table: str, column: str) -> bool:
    from sqlalchemy import text
    result = conn.execute(text(
        "SELECT COUNT(*) FROM information_schema.COLUMNS "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :t AND COLUMN_NAME = :c"
    ), {"t": table, "c": column})
    return result.scalar() > 0


def _index_exists(conn, table: str, index: str) -> bool:
    from sqlalchemy import text
    result = conn.execute(text(
        "SELECT COUNT(*) FROM information_schema.STATISTICS "
        "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = :t AND INDEX_NAME = :i"
    ), {"t": table, "i": index})
    return result.scalar() > 0


def upgrade() -> None:
    """Upgrade schema — idempotent: safe to run even if partly applied."""
    from sqlalchemy import text
    conn = op.get_bind()

    # 1. Create table (IF NOT EXISTS — already exists on some servers)
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS merged_po_change_logs (
            id          INTEGER NOT NULL AUTO_INCREMENT,
            merged_po_id INTEGER NOT NULL,
            po_id       VARCHAR(255) NOT NULL,
            site_code   VARCHAR(100),
            item_description VARCHAR(500),
            changed_by_user_id INTEGER NOT NULL,
            changed_at  DATETIME,
            action_type VARCHAR(50) NOT NULL,
            changes     JSON NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY (changed_by_user_id) REFERENCES users (id),
            FOREIGN KEY (merged_po_id)       REFERENCES merged_pos (id) ON DELETE CASCADE
        )
    """))

    # 2. Indexes (skip if already present)
    for idx, col in [
        ('ix_merged_po_change_logs_changed_at',   'changed_at'),
        ('ix_merged_po_change_logs_id',            'id'),
        ('ix_merged_po_change_logs_merged_po_id',  'merged_po_id'),
        ('ix_merged_po_change_logs_po_id',         'po_id'),
    ]:
        if not _index_exists(conn, 'merged_po_change_logs', idx):
            conn.execute(text(f"CREATE INDEX `{idx}` ON merged_po_change_logs (`{col}`)"))

    # 3. New columns on merged_pos (skip each if already present)
    new_cols = [
        ("status_installation",    "VARCHAR(100)"),
        ("date_installation",      "DATE"),
        ("need_document",          "VARCHAR(10)"),
        ("date_document_ok",       "DATE"),
        ("remark_last_remark",     "TEXT"),
        ("readiness_acceptance",   "VARCHAR(100)"),
        ("rejection_remark",       "TEXT"),
        ("remarks",                "TEXT"),
        ("status_report_isdp",     "VARCHAR(50)"),
        ("date_close_report_isdp", "DATE"),
        ("remark_qc_reason",       "TEXT"),
    ]
    for col_name, col_type in new_cols:
        if not _col_exists(conn, 'merged_pos', col_name):
            conn.execute(text(f"ALTER TABLE merged_pos ADD COLUMN `{col_name}` {col_type} NULL"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merged_pos', 'remark_qc_reason')
    op.drop_column('merged_pos', 'date_close_report_isdp')
    op.drop_column('merged_pos', 'status_report_isdp')
    op.drop_column('merged_pos', 'remarks')
    op.drop_column('merged_pos', 'rejection_remark')
    op.drop_column('merged_pos', 'readiness_acceptance')
    op.drop_column('merged_pos', 'remark_last_remark')
    op.drop_column('merged_pos', 'date_document_ok')
    op.drop_column('merged_pos', 'need_document')
    op.drop_column('merged_pos', 'date_installation')
    op.drop_column('merged_pos', 'status_installation')
    op.drop_index(op.f('ix_merged_po_change_logs_po_id'), table_name='merged_po_change_logs')
    op.drop_index(op.f('ix_merged_po_change_logs_merged_po_id'), table_name='merged_po_change_logs')
    op.drop_index(op.f('ix_merged_po_change_logs_id'), table_name='merged_po_change_logs')
    op.drop_index(op.f('ix_merged_po_change_logs_changed_at'), table_name='merged_po_change_logs')
    op.drop_table('merged_po_change_logs')
    # ### end Alembic commands ###
